#!/bin/bash

CLICKUP_DIR="/opt/clickup"

find_latest_appimage() {
  find "$CLICKUP_DIR" -name "*.AppImage" -type f -printf '%T@ %p\n' \
    | sort -nr \
    | head -n1 \
    | cut -d' ' -f2-
}

CLICKUP_APPIMAGE=$(find_latest_appimage)

if [ ! -s "$CLICKUP_APPIMAGE" ]; then
  echo "Error: No ClickUp AppImage file found in $CLICKUP_DIR"
  exit 1
fi 

if [ ! -x "$CLICKUP_APPIMAGE" ]; then
    echo "Adding execution permissions to $CLICKUP_APPIMAGE"
    chmod +x "$CLICKUP_APPIMAGE"
fi 

exec "$CLICKUP_APPIMAGE" "$@"
